stages:
  - install_deps
  - build

default:
  image: node:lts-alpine

install_deps:
  stage: install_deps
  cache:
    - key:
        files:
        - package-lock.json
      paths:
        - node_modules
      policy: pull
    - key: build-$CI_JOB_IMAGE
      policy: pull-push
  script: 
    - npm install

