image: node:lts-alpine

stages:
  - install_deps
  - build

install_dependencies:
  stage: install_deps
  script:
    - npm install
  artifacts:
    paths:
      - node_modules

build:
  stage: build
  cache:
    - key:
        files:
        - package-lock.json
      paths:
        - node_modules
      policy: pull
  script: 
    - npm run build

