version: '3.1'
services:
  db:
    image: mysql
    restart: always
    env_file:
      - ./.env.db
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
  service_api:
      container_name: api_service
      image: node:16
      working_dir:  /usr/src/cms-brave
      restart: always
      command: bash -c "npm install && npm run debug"
      volumes:
      - ./src/:/usr/src/cms-brave/src/
      - ./package.json:/usr/src/cms-brave/package.json
      ports:
      - "5050:5050"
      depends_on:
      - db
      env_file:
      - ./.env
