version: '3.3'
services:
  service_api:
      container_name: api_service
      image: node:16
      working_dir:  /usr/src/cms-brave
      restart: always
      command: bash -c "npm install && npm run debug"
      volumes:
      - ./dist/:/usr/src/cms-brave/dist/
      - ./package.json:/usr/src/cms-brave/package.json
      ports:
      - "5050:5050"