version: '3.1'
services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    env_file:
      - ./.env.db
    ports:
      - 3306:3306
    volumes:
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./data:/var/lib/mysql
  service_api:
      container_name: api_service
      entrypoint: wait-for db:3306 -t 40 -- ./start.sh
      image: node:16
      restart: always
      build:
        context: ./
        dockerfile: Dockerfile
      volumes:
      - ./src/:/usr/src/cms-brave/src/
      - ./dist/:/usr/src/cms-brave/dist/
      - ./logs/:/usr/src/cms-brave/logs/
      - ./package.json:/usr/src/cms-brave/package.json
      ports:
      - "5050:5050"
      depends_on:
      - db
      env_file:
      - ./.env
