version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.17.6
    parallelism: 5
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install the dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - "./node_modules"
      - run:
          name: check code style
          command: npx eslint 'src/**'
      - run:
          name: tests and generates coverage report
          command: |
                    TEST=$(circleci tests glob "src/**/*.spec.ts" "src/**/*.test.ts" | circleci tests split --split-by=timings)
                    npm run test $TEST
